FROM python:3.11-alpine
ENV PORT=8080
WORKDIR /app
COPY requirements_syncfusion.txt requirements.txt
RUN pip install -r requirements.txt
COPY syncfusion_enhanced_watson.py main.py
EXPOSE 8080
CMD ["gunicorn", "--bind", ":8080", "--workers", "1", "main:app"]