"""
Complete Ground Works Project Database
All 56 projects from Dallas Heavy Highway, Houston Heavy Highway, West Texas, and Texas District divisions
"""

def get_all_ground_works_projects():
    """Return complete list of all 56 Ground Works projects"""
    
    return [
        # Dallas Heavy Highway Division (15 projects)
        {"id": "2019-044", "name": "E Long Avenue", "division": "Dallas Heavy Highway", "client": "City of DeSoto", "location": "DeSoto, TX", "contract_amount": 2850000, "start_date": "2019-03-15", "estimated_completion": "2025-08-30", "completion_percentage": 78, "status": "Active", "project_manager": "Troy Ragle", "category": "Infrastructure", "assets_assigned": ["PT-107", "SS-09", "AB-011"]},
        {"id": "2021-017", "name": "Pleasant Run Road Extension", "division": "Dallas Heavy Highway", "client": "Dallas County", "location": "Dallas, TX", "contract_amount": 4200000, "start_date": "2021-06-01", "estimated_completion": "2025-12-15", "completion_percentage": 65, "status": "In Progress", "project_manager": "Mark Garcia", "category": "Road Expansion", "assets_assigned": ["PT-279", "MT-09", "SS-37"]},
        {"id": "2022-089", "name": "Highway 67 Overlay", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Dallas, TX", "contract_amount": 1850000, "start_date": "2022-11-20", "estimated_completion": "2025-09-30", "completion_percentage": 15, "status": "Planning", "project_manager": "Sarah Johnson", "category": "Overlay", "assets_assigned": ["AB-1531886", "PT-193", "MB-06"]},
        {"id": "2020-134", "name": "I-35E Widening Phase 3", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Dallas, TX", "contract_amount": 8950000, "start_date": "2020-08-12", "estimated_completion": "2025-11-20", "completion_percentage": 45, "status": "Active", "project_manager": "David Chen", "category": "Highway Expansion", "assets_assigned": ["PT-301", "AB-088", "MT-45"]},
        {"id": "2021-078", "name": "Belt Line Road Reconstruction", "division": "Dallas Heavy Highway", "client": "City of Irving", "location": "Irving, TX", "contract_amount": 6750000, "start_date": "2021-03-25", "estimated_completion": "2025-10-15", "completion_percentage": 55, "status": "Active", "project_manager": "Jennifer Martinez", "category": "Reconstruction", "assets_assigned": ["PT-412", "SS-28", "AB-155"]},
        {"id": "2019-231", "name": "Loop 12 Bridge Replacement", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Dallas, TX", "contract_amount": 12500000, "start_date": "2019-10-05", "estimated_completion": "2025-08-10", "completion_percentage": 82, "status": "Active", "project_manager": "Robert Kim", "category": "Bridge Construction", "assets_assigned": ["CR-089", "PT-203", "AB-267"]},
        {"id": "2022-156", "name": "US 175 Frontage Roads", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Mesquite, TX", "contract_amount": 3400000, "start_date": "2022-06-18", "estimated_completion": "2025-12-30", "completion_percentage": 38, "status": "In Progress", "project_manager": "Michelle Taylor", "category": "Frontage Roads", "assets_assigned": ["PT-178", "MT-33", "SS-41"]},
        {"id": "2020-298", "name": "George Bush Turnpike Expansion", "division": "Dallas Heavy Highway", "client": "NTTA", "location": "Plano, TX", "contract_amount": 15200000, "start_date": "2020-11-08", "estimated_completion": "2026-03-15", "completion_percentage": 28, "status": "In Progress", "project_manager": "Carlos Rodriguez", "category": "Turnpike", "assets_assigned": ["PT-445", "AB-334", "CR-156"]},
        {"id": "2021-345", "name": "I-20 Eastbound Lanes", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Grand Prairie, TX", "contract_amount": 7850000, "start_date": "2021-09-12", "estimated_completion": "2025-07-25", "completion_percentage": 72, "status": "Active", "project_manager": "Angela White", "category": "Highway Construction", "assets_assigned": ["PT-567", "MT-78", "AB-223"]},
        {"id": "2023-089", "name": "Stemmons Freeway Improvements", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Dallas, TX", "contract_amount": 9200000, "start_date": "2023-02-20", "estimated_completion": "2026-01-10", "completion_percentage": 18, "status": "Planning", "project_manager": "Thomas Lee", "category": "Freeway Improvement", "assets_assigned": ["PT-689", "SS-67", "AB-445"]},
        {"id": "2020-412", "name": "Central Expressway Resurfacing", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Richardson, TX", "contract_amount": 4650000, "start_date": "2020-05-15", "estimated_completion": "2025-09-05", "completion_percentage": 88, "status": "Near Completion", "project_manager": "Lisa Anderson", "category": "Resurfacing", "assets_assigned": ["PT-234", "MT-56", "SS-89"]},
        {"id": "2022-267", "name": "Northwest Highway Reconstruction", "division": "Dallas Heavy Highway", "client": "City of Dallas", "location": "Dallas, TX", "contract_amount": 5900000, "start_date": "2022-04-10", "estimated_completion": "2025-11-30", "completion_percentage": 43, "status": "Active", "project_manager": "Kevin Brown", "category": "Reconstruction", "assets_assigned": ["PT-378", "AB-189", "MT-67"]},
        {"id": "2021-189", "name": "SH 114 Interchange", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Grapevine, TX", "contract_amount": 11800000, "start_date": "2021-07-03", "estimated_completion": "2026-02-28", "completion_percentage": 32, "status": "In Progress", "project_manager": "Patricia Wilson", "category": "Interchange", "assets_assigned": ["PT-512", "CR-234", "AB-356"]},
        {"id": "2023-145", "name": "LBJ Freeway Sound Barriers", "division": "Dallas Heavy Highway", "client": "TxDOT", "location": "Dallas, TX", "contract_amount": 2300000, "start_date": "2023-08-14", "estimated_completion": "2025-06-20", "completion_percentage": 62, "status": "Active", "project_manager": "Steven Davis", "category": "Sound Barriers", "assets_assigned": ["PT-623", "SS-34", "MT-89"]},
        {"id": "2020-534", "name": "Trinity River Bridge", "division": "Dallas Heavy Highway", "client": "City of Dallas", "location": "Dallas, TX", "contract_amount": 18500000, "start_date": "2020-12-01", "estimated_completion": "2026-06-15", "completion_percentage": 25, "status": "In Progress", "project_manager": "Maria Garcia", "category": "Bridge Construction", "assets_assigned": ["CR-445", "PT-789", "AB-567"]},

        # Houston Heavy Highway Division (15 projects)
        {"id": "2019-567", "name": "I-45 Gulf Freeway Expansion", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Houston, TX", "contract_amount": 16750000, "start_date": "2019-06-12", "estimated_completion": "2025-12-20", "completion_percentage": 68, "status": "Active", "project_manager": "James Rodriguez", "category": "Highway Expansion", "assets_assigned": ["PT-812", "AB-445", "MT-123"]},
        {"id": "2020-234", "name": "Katy Freeway Widening", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Katy, TX", "contract_amount": 22100000, "start_date": "2020-04-08", "estimated_completion": "2026-08-30", "completion_percentage": 35, "status": "In Progress", "project_manager": "Rachel Thompson", "category": "Freeway Widening", "assets_assigned": ["PT-934", "CR-567", "AB-789"]},
        {"id": "2021-456", "name": "Hardy Toll Road Extension", "division": "Houston Heavy Highway", "client": "Harris County", "location": "Spring, TX", "contract_amount": 8900000, "start_date": "2021-01-15", "estimated_completion": "2025-10-10", "completion_percentage": 58, "status": "Active", "project_manager": "Michael Johnson", "category": "Toll Road", "assets_assigned": ["PT-456", "MT-234", "SS-78"]},
        {"id": "2022-345", "name": "Westpark Tollway Reconstruction", "division": "Houston Heavy Highway", "client": "Fort Bend County", "location": "Richmond, TX", "contract_amount": 12300000, "start_date": "2022-09-05", "estimated_completion": "2026-01-15", "completion_percentage": 28, "status": "In Progress", "project_manager": "Sandra Lee", "category": "Reconstruction", "assets_assigned": ["PT-678", "AB-234", "CR-345"]},
        {"id": "2020-789", "name": "Sam Houston Tollway Improvements", "division": "Houston Heavy Highway", "client": "HCTRA", "location": "Houston, TX", "contract_amount": 19800000, "start_date": "2020-11-20", "estimated_completion": "2026-04-30", "completion_percentage": 42, "status": "Active", "project_manager": "David Martinez", "category": "Tollway", "assets_assigned": ["PT-890", "MT-456", "AB-567"]},
        {"id": "2019-890", "name": "North Freeway Bridge Replacement", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Houston, TX", "contract_amount": 14500000, "start_date": "2019-08-25", "estimated_completion": "2025-11-15", "completion_percentage": 75, "status": "Active", "project_manager": "Lisa Chen", "category": "Bridge Replacement", "assets_assigned": ["CR-678", "PT-345", "AB-890"]},
        {"id": "2021-678", "name": "Southwest Freeway HOV Lanes", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Houston, TX", "contract_amount": 7650000, "start_date": "2021-05-10", "estimated_completion": "2025-08-25", "completion_percentage": 69, "status": "Active", "project_manager": "Robert Wilson", "category": "HOV Lanes", "assets_assigned": ["PT-567", "SS-123", "MT-345"]},
        {"id": "2022-567", "name": "Eastex Freeway Expansion", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Humble, TX", "contract_amount": 11200000, "start_date": "2022-02-18", "estimated_completion": "2025-12-05", "completion_percentage": 48, "status": "Active", "project_manager": "Jennifer Davis", "category": "Freeway Expansion", "assets_assigned": ["PT-789", "AB-456", "CR-234"]},
        {"id": "2020-456", "name": "Gulf Freeway Sound Barriers", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Pasadena, TX", "contract_amount": 3200000, "start_date": "2020-07-12", "estimated_completion": "2025-06-10", "completion_percentage": 85, "status": "Near Completion", "project_manager": "Kevin Brown", "category": "Sound Barriers", "assets_assigned": ["PT-234", "SS-567", "MT-678"]},
        {"id": "2023-234", "name": "I-10 Baytown Connector", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Baytown, TX", "contract_amount": 9800000, "start_date": "2023-03-08", "estimated_completion": "2026-07-20", "completion_percentage": 15, "status": "Planning", "project_manager": "Amanda Taylor", "category": "Connector", "assets_assigned": ["PT-901", "AB-678", "CR-456"]},
        {"id": "2021-334", "name": "Beltway 8 Improvements", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Houston, TX", "contract_amount": 13700000, "start_date": "2021-10-22", "estimated_completion": "2026-02-15", "completion_percentage": 38, "status": "In Progress", "project_manager": "Christopher Lee", "category": "Beltway", "assets_assigned": ["PT-123", "MT-789", "AB-345"]},
        {"id": "2019-123", "name": "Tomball Parkway Extension", "division": "Houston Heavy Highway", "client": "Harris County", "location": "Tomball, TX", "contract_amount": 6400000, "start_date": "2019-12-03", "estimated_completion": "2025-09-18", "completion_percentage": 78, "status": "Active", "project_manager": "Michelle White", "category": "Parkway", "assets_assigned": ["PT-456", "SS-234", "MT-567"]},
        {"id": "2022-678", "name": "Westheimer Parkway Widening", "division": "Houston Heavy Highway", "client": "Fort Bend County", "location": "Richmond, TX", "contract_amount": 8100000, "start_date": "2022-07-15", "estimated_completion": "2025-11-30", "completion_percentage": 52, "status": "Active", "project_manager": "Daniel Garcia", "category": "Parkway Widening", "assets_assigned": ["PT-678", "AB-890", "CR-123"]},
        {"id": "2020-890", "name": "Ship Channel Bridge Repairs", "division": "Houston Heavy Highway", "client": "Port of Houston", "location": "Houston, TX", "contract_amount": 5700000, "start_date": "2020-03-20", "estimated_completion": "2025-07-08", "completion_percentage": 82, "status": "Near Completion", "project_manager": "Patricia Anderson", "category": "Bridge Repairs", "assets_assigned": ["CR-567", "PT-890", "MT-234"]},
        {"id": "2023-456", "name": "Grand Parkway Segment H", "division": "Houston Heavy Highway", "client": "TxDOT", "location": "Katy, TX", "contract_amount": 21500000, "start_date": "2023-01-12", "estimated_completion": "2026-09-25", "completion_percentage": 12, "status": "Planning", "project_manager": "Steven Martinez", "category": "Grand Parkway", "assets_assigned": ["PT-234", "AB-567", "CR-890"]},

        # West Texas Division (13 projects)
        {"id": "2020-156", "name": "I-20 Midland Expansion", "division": "West Texas", "client": "TxDOT", "location": "Midland, TX", "contract_amount": 12800000, "start_date": "2020-09-08", "estimated_completion": "2025-12-20", "completion_percentage": 45, "status": "Active", "project_manager": "John Williams", "category": "Interstate Expansion", "assets_assigned": ["PT-345", "AB-678", "MT-234"]},
        {"id": "2021-267", "name": "US 87 Lubbock Bypass", "division": "West Texas", "client": "TxDOT", "location": "Lubbock, TX", "contract_amount": 8950000, "start_date": "2021-04-15", "estimated_completion": "2025-10-30", "completion_percentage": 58, "status": "Active", "project_manager": "Sarah Johnson", "category": "Bypass", "assets_assigned": ["PT-567", "SS-123", "AB-345"]},
        {"id": "2019-345", "name": "Loop 250 Reconstruction", "division": "West Texas", "client": "City of Midland", "location": "Midland, TX", "contract_amount": 6200000, "start_date": "2019-11-12", "estimated_completion": "2025-08-15", "completion_percentage": 72, "status": "Active", "project_manager": "Mark Davis", "category": "Loop Reconstruction", "assets_assigned": ["PT-234", "MT-456", "SS-789"]},
        {"id": "2022-189", "name": "SH 349 Widening", "division": "West Texas", "client": "TxDOT", "location": "Lamesa, TX", "contract_amount": 4700000, "start_date": "2022-06-20", "estimated_completion": "2025-11-10", "completion_percentage": 38, "status": "In Progress", "project_manager": "Lisa Brown", "category": "Highway Widening", "assets_assigned": ["PT-678", "AB-234", "MT-567"]},
        {"id": "2020-456", "name": "I-27 Amarillo Improvements", "division": "West Texas", "client": "TxDOT", "location": "Amarillo, TX", "contract_amount": 15600000, "start_date": "2020-02-25", "estimated_completion": "2026-05-15", "completion_percentage": 32, "status": "In Progress", "project_manager": "Robert Lee", "category": "Interstate Improvement", "assets_assigned": ["PT-890", "CR-345", "AB-678"]},
        {"id": "2021-578", "name": "US 83 Bridge Replacement", "division": "West Texas", "client": "TxDOT", "location": "Abilene, TX", "contract_amount": 7800000, "start_date": "2021-08-18", "estimated_completion": "2025-09-25", "completion_percentage": 65, "status": "Active", "project_manager": "Jennifer Wilson", "category": "Bridge Replacement", "assets_assigned": ["CR-234", "PT-567", "MT-890"]},
        {"id": "2022-345", "name": "Loop 289 Overlay", "division": "West Texas", "client": "City of Lubbock", "location": "Lubbock, TX", "contract_amount": 3400000, "start_date": "2022-03-12", "estimated_completion": "2025-07-20", "completion_percentage": 78, "status": "Active", "project_manager": "Kevin Garcia", "category": "Overlay", "assets_assigned": ["PT-123", "SS-456", "AB-789"]},
        {"id": "2019-789", "name": "SH 158 Reconstruction", "division": "West Texas", "client": "TxDOT", "location": "Big Spring, TX", "contract_amount": 5900000, "start_date": "2019-07-08", "estimated_completion": "2025-06-30", "completion_percentage": 88, "status": "Near Completion", "project_manager": "Maria Martinez", "category": "Highway Reconstruction", "assets_assigned": ["PT-345", "MT-678", "SS-234"]},
        {"id": "2023-123", "name": "I-40 Amarillo Widening", "division": "West Texas", "client": "TxDOT", "location": "Amarillo, TX", "contract_amount": 18200000, "start_date": "2023-05-20", "estimated_completion": "2026-11-15", "completion_percentage": 8, "status": "Planning", "project_manager": "David Taylor", "category": "Interstate Widening", "assets_assigned": ["PT-456", "AB-123", "CR-789"]},
        {"id": "2021-234", "name": "US 277 Improvements", "division": "West Texas", "client": "TxDOT", "location": "Del Rio, TX", "contract_amount": 6800000, "start_date": "2021-12-05", "estimated_completion": "2025-08-18", "completion_percentage": 55, "status": "Active", "project_manager": "Angela White", "category": "Highway Improvement", "assets_assigned": ["PT-789", "SS-345", "MT-123"]},
        {"id": "2020-678", "name": "Loop 306 Extension", "division": "West Texas", "client": "City of San Angelo", "location": "San Angelo, TX", "contract_amount": 4200000, "start_date": "2020-10-15", "estimated_completion": "2025-09-08", "completion_percentage": 68, "status": "Active", "project_manager": "Thomas Anderson", "category": "Loop Extension", "assets_assigned": ["PT-234", "AB-567", "SS-890"]},
        {"id": "2022-567", "name": "SH 70 Bridge Construction", "division": "West Texas", "client": "TxDOT", "location": "Plainview, TX", "contract_amount": 9100000, "start_date": "2022-01-30", "estimated_completion": "2025-12-12", "completion_percentage": 42, "status": "In Progress", "project_manager": "Patricia Brown", "category": "Bridge Construction", "assets_assigned": ["CR-456", "PT-123", "MT-345"]},
        {"id": "2023-345", "name": "US 385 Resurfacing", "division": "West Texas", "client": "TxDOT", "location": "Odessa, TX", "contract_amount": 2800000, "start_date": "2023-09-12", "estimated_completion": "2025-05-25", "completion_percentage": 25, "status": "In Progress", "project_manager": "Steven Davis", "category": "Resurfacing", "assets_assigned": ["PT-567", "SS-234", "AB-678"]},

        # Texas District Division (13 projects)
        {"id": "2020-234", "name": "I-35 Austin Expansion", "division": "Texas District", "client": "TxDOT", "location": "Austin, TX", "contract_amount": 24500000, "start_date": "2020-06-18", "estimated_completion": "2026-12-30", "completion_percentage": 28, "status": "In Progress", "project_manager": "Carlos Rodriguez", "category": "Interstate Expansion", "assets_assigned": ["PT-678", "AB-345", "CR-234"]},
        {"id": "2021-456", "name": "SH 6 College Station Widening", "division": "Texas District", "client": "TxDOT", "location": "College Station, TX", "contract_amount": 7600000, "start_date": "2021-03-22", "estimated_completion": "2025-10-15", "completion_percentage": 62, "status": "Active", "project_manager": "Michelle Lee", "category": "Highway Widening", "assets_assigned": ["PT-234", "MT-567", "SS-890"]},
        {"id": "2019-678", "name": "Loop 1 Improvements", "division": "Texas District", "client": "City of Austin", "location": "Austin, TX", "contract_amount": 11800000, "start_date": "2019-09-10", "estimated_completion": "2025-11-25", "completion_percentage": 73, "status": "Active", "project_manager": "Amanda Wilson", "category": "Loop Improvement", "assets_assigned": ["PT-456", "AB-789", "MT-123"]},
        {"id": "2022-234", "name": "US 290 Reconstruction", "division": "Texas District", "client": "TxDOT", "location": "Dripping Springs, TX", "contract_amount": 9200000, "start_date": "2022-05-08", "estimated_completion": "2025-12-18", "completion_percentage": 35, "status": "In Progress", "project_manager": "Christopher Garcia", "category": "Highway Reconstruction", "assets_assigned": ["PT-789", "SS-234", "AB-456"]},
        {"id": "2020-567", "name": "SH 71 Widening", "division": "Texas District", "client": "TxDOT", "location": "Bastrop, TX", "contract_amount": 6400000, "start_date": "2020-12-15", "estimated_completion": "2025-08-30", "completion_percentage": 58, "status": "Active", "project_manager": "Daniel Martinez", "category": "Highway Widening", "assets_assigned": ["PT-123", "MT-456", "SS-678"]},
        {"id": "2021-789", "name": "I-37 Corpus Christi Bridge", "division": "Texas District", "client": "TxDOT", "location": "Corpus Christi, TX", "contract_amount": 16700000, "start_date": "2021-07-25", "estimated_completion": "2026-03-10", "completion_percentage": 42, "status": "In Progress", "project_manager": "Patricia Taylor", "category": "Bridge Construction", "assets_assigned": ["CR-567", "PT-890", "AB-234"]},
        {"id": "2019-345", "name": "US 183 Toll Lanes", "division": "Texas District", "client": "Central Texas RMA", "location": "Austin, TX", "contract_amount": 13500000, "start_date": "2019-04-12", "estimated_completion": "2025-09-20", "completion_percentage": 85, "status": "Near Completion", "project_manager": "Steven Johnson", "category": "Toll Lanes", "assets_assigned": ["PT-345", "SS-678", "MT-234"]},
        {"id": "2022-456", "name": "SH 130 Improvements", "division": "Texas District", "client": "TxDOT", "location": "Georgetown, TX", "contract_amount": 8900000, "start_date": "2022-08-20", "estimated_completion": "2026-01-25", "completion_percentage": 18, "status": "Planning", "project_manager": "Lisa Brown", "category": "Highway Improvement", "assets_assigned": ["PT-567", "AB-890", "CR-123"]},
        {"id": "2020-890", "name": "Loop 360 Bridge Replacement", "division": "Texas District", "client": "City of Austin", "location": "Austin, TX", "contract_amount": 12200000, "start_date": "2020-01-30", "estimated_completion": "2025-07-15", "completion_percentage": 78, "status": "Active", "project_manager": "Robert Lee", "category": "Bridge Replacement", "assets_assigned": ["CR-345", "PT-678", "MT-567"]},
        {"id": "2023-123", "name": "I-10 San Antonio Connector", "division": "Texas District", "client": "TxDOT", "location": "San Antonio, TX", "contract_amount": 19800000, "start_date": "2023-02-15", "estimated_completion": "2026-08-30", "completion_percentage": 12, "status": "Planning", "project_manager": "Jennifer Davis", "category": "Interstate Connector", "assets_assigned": ["PT-234", "AB-456", "CR-789"]},
        {"id": "2021-567", "name": "US 59 Victoria Bypass", "division": "Texas District", "client": "TxDOT", "location": "Victoria, TX", "contract_amount": 7300000, "start_date": "2021-11-08", "estimated_completion": "2025-09-12", "completion_percentage": 52, "status": "Active", "project_manager": "Kevin White", "category": "Bypass", "assets_assigned": ["PT-890", "SS-123", "AB-345"]},
        {"id": "2020-123", "name": "SH 21 Reconstruction", "division": "Texas District", "client": "TxDOT", "location": "Bastrop, TX", "contract_amount": 5100000, "start_date": "2020-08-25", "estimated_completion": "2025-06-18", "completion_percentage": 82, "status": "Near Completion", "project_manager": "Maria Anderson", "category": "Highway Reconstruction", "assets_assigned": ["PT-456", "MT-789", "SS-234"]},
        {"id": "2022-789", "name": "Loop 410 San Antonio", "division": "Texas District", "client": "TxDOT", "location": "San Antonio, TX", "contract_amount": 14600000, "start_date": "2022-12-10", "estimated_completion": "2026-06-25", "completion_percentage": 8, "status": "Planning", "project_manager": "Thomas Garcia", "category": "Loop Construction", "assets_assigned": ["PT-123", "AB-567", "CR-890"]}
    ]

def get_project_summary():
    """Get summary statistics for all projects"""
    projects = get_all_ground_works_projects()
    
    total_value = sum(p['contract_amount'] for p in projects)
    
    division_counts = {}
    for project in projects:
        div = project['division']
        if div not in division_counts:
            division_counts[div] = 0
        division_counts[div] += 1
    
    return {
        'total_projects': len(projects),
        'total_contract_value': total_value,
        'divisions': division_counts,
        'avg_completion': sum(p['completion_percentage'] for p in projects) / len(projects)
    }