apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traxovo-watson
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/traxovo-watson
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SESSION_SECRET
          value: "nexus_watson_supreme_production"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
  traffic:
  - percent: 100
    latestRevision: true